### ISSUE TITLE
Problem G identifier

### ISSUE THREAD

**Issue by axel578** [BitTheByte/YouTubeShop#10]
G_identifier:'str' object has no attribute 'get' , i found this problem , i used python 2.7 and 3.7 with youtubepy and youtubepy3 but nothing worket , even from cmd python it didn't work , there were no empty lines ...  :)

**Comment by BitTheByte** [comment]
Many issues are appearing from the Youtube's endpoints in the last 3 days .. maybe they're changing some internal code. Also I did notice that every other version is not working including current version. I think i'll need to rewrite a huge section of the code in order to work with the new updates
In the mean time any help is appreciated.

**Comment by BitTheByte** [comment]
Well.. there is a fix and has been deployed however i tested it on a few accounts and resulted in a some false positives i'll keep it untill i push a permanent fix , can you check if that solved your problem? 
 py3:https://github.com/BitTheByte/YouTubeShop/commit/a1f71ab310d6f77fcf5ad9e53e532aa46e34a7bf & py2:https://github.com/BitTheByte/YouTubeShop/commit/0c4cfa464a3445f5da4c0268f07385985f775e98

**Comment by axel578** [comment]
i tried once again and I got : [E] YoutubeLike:'v' , thanks for fast answer and sorry i am a big nooby in python :)

**Comment by BitTheByte** [comment]
Could you please post a sample from your emails and YouTube URL text files ?
just a 5 or 6 lines to not to spam the issue.

**Comment by axel578** [comment]
its in this way : 
mail@gmail.com:password
mail@gmail.com:password
mail@gmail.com:password
mail@gmail.com:password

in youtube url in fact it's just the id of the video

**Comment by BitTheByte** [comment]
I afraid you maybe using this program the wrong way.

The format of emails.txt needs to be like this:-

```
Mail@XXX.com:password
Mail@XXX.com:password
```

And the format of urls.txt needs to be like this :-

In case of you want to like a video 
```
https://youtube.com/watch?v=xxxxx
https://youtube.com/watch?v=xxxxx
https://youtube.com/watch?v=xxxxx
```

Or subscribe to channel
```
https://youtube.com/channel/xxxxxx
https://youtube.com/channel/xxxxxx
```

I know, it's a bit silly to put the full URL instead of video id or channel's id but changing that now'll confuse some people

**Comment by BitTheByte** [comment]
Closed for inactivity
