### ISSUE TITLE
Bot dont work (like and subs)

### ISSUE THREAD

**Issue by towuk118** [BitTheByte/YouTubeShop#29]
i have many accounts and finished requests, but dont work likes and subs!(

**Comment by BitTheByte** [comment]
Hey @towuk118 

Thanks for contacting me, I'm already working on this. You'll be hearing from me soon

**Comment by towuk118** [comment]
Thanks for taking the time to this issue.

**Comment by BitTheByte** [comment]
Hello @towuk118 

I'm happy to announce that this issue has been fixed at the current release https://github.com/BitTheByte/YouTubeShop/commit/b5f9415d3972f2b088fe69282e806e53d9361744. May you please confirm the fixed on your end? the confirmation process should not exceed 7 days (week) otherwise I'll close this issue as resolved

**Comment by towuk118** [comment]
i go testing...

**Comment by towuk118** [comment]
Traceback (most recent call last):
  File "yt.py", line 69, in <module>
    for credentials in cli.read_acounts_file(accounts_path):
  File "C:\Users\towuk\Desktop\YouTubeShop-master\lib\cli.py", line 96, in read_acounts_file
    email,password = line.strip().split(":")
ValueError: too many values to unpack

**Comment by BitTheByte** [comment]
Please stay with the emails combo format as said at the README.md file
